-- MySQL Script generated by MySQL Workbench
-- Wed Jul  6 18:24:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myBlog
-- -----------------------------------------------------
-- Practica de master en PHP 06/07/2022.

-- -----------------------------------------------------
-- Schema myBlog
--
-- Practica de master en PHP 06/07/2022.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myBlog` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `myBlog` ;

-- -----------------------------------------------------
-- Table `myBlog`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myBlog`.`USUARIOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myBlog`.`CATEGORIAS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`ENTRADAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myBlog`.`ENTRADAS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descripcion` MEDIUMTEXT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_categoria_id_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `myBlog`.`USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_id`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `myBlog`.`CATEGORIAS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
